### ISSUE TITLE
Feature Request for separator

### ISSUE THREAD

**Issue by ashikur11** [mobilejazz/MJ-WP-Breadcrumb#2]
Please make an option for breadcrumbs separators.
http://prntscr.com/lny7li like this :)

**Comment by adchsm** [comment]
Hey @ashikur11, thanks for the request. This breadcrumb comes with no styling on purpose - so you adapt it however you want. You can add any separators you like through css, for example:

```
.breadcrumb li:not(:last-child):after {
  content: "-";
}
```

I hope that helps,

Thanks,

Adam

**Comment by ashikur11** [comment]
Yeah i did like that :)
